main: fr.northenflo.permiflow.Main
name: PermiFlow
version: '1.0'
description: A plugin permission
author: NorthenFlo
website: northenflo.xyz
commands:
  pfreload:
    description: Reload plugin config
    usage: /pfreload
    permission: permiflow.reload
  pfgroup:
    description: Group Actions
    usage: /pfgroup
    permission: permiflow.group.*
  pfplayer:
    description: Player Actions
    usage: /pfplayer
    permission: permiflow.player.*